/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sahan.view;

import com.sahan.observer.SubscriptionObserver;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahan Nimesha
 */
public class ChannelScreen extends javax.swing.JFrame {

    private SubscriptionObserver subscriptionObserver;
    private String channel;
    /**
     * Creates new form ChannelScreen
     */
    public ChannelScreen() {
        initComponents();
    }

    public ChannelScreen(SubscriptionObserver subscriptionObserver) {
        this();
        this.subscriptionObserver = subscriptionObserver;
        
        String temp = JOptionPane.showInputDialog(this, "Channel Name :");
        this.channel = temp.trim();
        this.subscriptionObserver.createChannel(this.channel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCaptionHome = new javax.swing.JLabel();
        btnPublish = new javax.swing.JButton();
        txtMsg = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCaptionHome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCaptionHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaptionHome.setText("CHANNEL WIZARD");

        btnPublish.setBackground(new java.awt.Color(51, 0, 255));
        btnPublish.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPublish.setText("PUBLISH");
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublishActionPerformed(evt);
            }
        });

        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCaptionHome, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMsg)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCaptionHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPublish)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishActionPerformed
        subscriptionObserver.sendMessage(this.channel , txtMsg.getText());
        txtMsg.setText("");
    }//GEN-LAST:event_btnPublishActionPerformed

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgActionPerformed
        // add your handling code here:
    }//GEN-LAST:event_txtMsgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCaptionHome;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
